# .github/release.yml

changelog: 
  categories: 
    - title: Vehicles
      labels: 
        - vehicle
    - title: Updates
      labels: 
        - maintain
    - title: Other Changes
      labels: 
        - "*"
