# .github/release.yml

changelog:
  exclude:
    labels:
      - bug
      - duplicate
      - good first issue
      - help wanted
      - internal
      - invalid
      - question
      - wontfix
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Vehicles
      labels:
        - vehicle
    - title: Updates
      labels:
        - maintain
    - title: Other Changes
      labels:
        - "*"
